#ifndef BGSUBTRACTOR_HPP
#define BGSUBTRACTOR_HPP

#include <opencv2/highgui.hpp>
#include <opencv2/video.hpp>


namespace VA {
    class BgSubtractor {
        private:
            cv::Mat foreground; //fg mask fg mask generated by MOG2 method
            cv::Ptr<cv::BackgroundSubtractor> pMOG2; //MOG2 Background subtractor

        public:
            BgSubtractor();

            ~BgSubtractor();

            /*
             * Finds frame forground and returns contours rectangles.
             */
            std::vector<cv::Rect> getForground(cv::Mat frame);
        
        private:
            void cleanNoise(cv::Mat& foreground); // Erode the frame
    }; // end of class
} // end of namespace

#endif
